---

- name: Variables In Playbook
  hosts: local
  connection: local
  vars:
    message: "HELLO ANSIBLE COURSE DURATION IS 10 HOURS" #VARS SHOULD BE REFERENCED WITH "" and should use {{ }}
    COURSE: DEVOPS
    TRAINER: SIVAKUMAR
  tasks:
      - name: PRINT COURSE & TUTOR INFORMATION
        debug: 
          msg: "{{ COURSE }} IS TEACHED BY {{ TRAINER }}"

      - name: PRINT ANSIBLE HOURS INFORMATION
        debug:
         msg: "{{ message }}"
