---

- name: Loops
  hosts: local
  connection: local
  tasks:
    - name: Print names
      debug: 
       msg: "Hi ra {{ item }}" # item here is reserved key word
      loop:
      - Suresh
      - Ramesh
      - Joseph
      - Raheem

- name: Install Packages
  hosts: frontend
  become: yes
  tasks:
    - name: Install Packages
      package:
       name: "{{ item }}"
       state: installed
      loop:
         - mysql
         - zip
        

- name: Install Packages
  hosts: frontend
  become: yes
  tasks:
    - name: Install Packages
      package:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
      loop:
         - { name: 'nginx', state: 'absent' }
         - { name: 'mysql', state: 'absent' }
         - { name: 'httpd', state: 'present'}
