---

- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect ls output to a file
    shell: 
       "ls -ltr > /tmp/output.txt"
    register: command_result

  - name: print the outcome
    debug:
      msg: "{{ command_result }}"

  - name: redirect ls output to a file using command
    command: 
        "ls -ltr"
    register: command_output
  
  - name: print the output
    debug:
      msg: "{{ command_output }}"
